const tintColor = '#0B84FF';

export default {
  tintColor,
  tabIconDefault: '#CCC',
  tabIconSelected: tintColor,
  errorBackground: 'red',
  errorText: '#FFF',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  noticeText: '#FFF',
  white: '#FFF',
  black: '#000',
  iosLightIcon: '#959595',
  iosDarkIcon: '#7D7E7D',
  iosLightBorder: '#B2B2B2',
  iosLightBar: '#F9F9F9',
  iosDarkBorder: '#262626',
  iosDarkBar: '#121212',
  iosLightTableBG: '#EFEFF4',
  iosLightTable: '#FFF',
  iosLightSeparator: '#C7C7CC',
  iosDarkTable: '#141414',
  iosDarkSeparator: '#3E3E40',
  iosSystemGray: '#8E8E93',
  iosLightSystemGray2: '#AEAEB2',
  iosLightSystemGray3: '#C7C7CC',
  iosLightSystemGray4: '#D1D1D6',
  iosLightSystemGray5: '#E5E5EA',
  iosLightSystemGray6: '#F2F2F7',
  iosDarkSystemGray2: '#636366',
  iosDarkSystemGray3: '#48484A',
  iosDarkSystemGray4: '#3A3A3C',
  iosDarkSystemGray5: '#2C2C2E',
  iosDarkSystemGray6: '#1C1C1E',
};
